version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "short_url"
      POSTGRES_USER: "fd239"
      POSTGRES_PASSWORD: "fd239"
    ports:
      - "5432:5432"